-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 17:48:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema defaultdb
-- -----------------------------------------------------
-- main database
-- 
DROP SCHEMA IF EXISTS `defaultdb` ;

-- -----------------------------------------------------
-- Schema defaultdb
--
-- main database
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `defaultdb` ;
USE `defaultdb` ;




-- -----------------------------------------------------
-- Table `defaultdb`.`medical_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`medical_history` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`medical_history` (
  `history_id` INT AUTO_INCREMENT PRIMARY KEY,
  `fk_medical_history_user_id` INT NOT NULL,
  `allergies` VARCHAR(45) NULL DEFAULT NULL,
  `conditions` VARCHAR(45) NULL DEFAULT NULL,
  `smoker` INT NULL DEFAULT NULL,
  `alcoholic` INT NULL DEFAULT NULL,
  `surgical_history` VARCHAR(45) NULL DEFAULT NULL,
  `family_medical_history` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `history_id` (`fk_medical_history_user_id` ASC) VISIBLE,
  CONSTRAINT `history_id`
    FOREIGN KEY (`fk_medical_history_user_id`)
    REFERENCES `defaultdb`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;






-- -----------------------------------------------------
-- Table `defaultdb`.`assessment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`assessment` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`medication` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `fk_user_id` INT NOT NULL,
  `username` VARCHAR(225) NULL DEFAULT NULL,
  `email` VARCHAR(225) NULL DEFAULT NULL,
  `score` INT NULL DEFAULT NULL,
  INDEX `id` (`fk_user_id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `defaultdb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




-- -----------------------------------------------------
-- Table `defaultdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`user` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `gender` CHAR(1) CHECK (gender IN ('M', 'F')),
  `age` INT NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,

  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;





INSERT INTO `defaultdb`.`user` 
(`id`, `username`, `password`, `age`, `gender`, `email`)
VALUES
(1, 'admin', 'pbkdf2:sha256:600000$pAsRDiBDmxSHfdEg$92636fe0bd7e56bc65a754affa38f709298a0c754cc7a29436b1caf999fbab71',
 35, 'M', 'admin@NourOrganization.com');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
